# Generated by Django 5.0.3 on 2024-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='')),
                ('content', models.TextField(verbose_name='Текст')),
                ('date_publisher', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('publisher', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
